version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}
  
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/ecoshop

    jenkins:
      image: jenkinsci/blueocean
      environment:
        #### WINDOWS ONLY ####
        - DOCKER_HOST=tcp://host.docker.internal:2375
      user: root
      ports:
        - "8080:8080"
        - "8443:8443"
        - "50000:50000"
      volumes:
        - ./jenkins_data:/var/jenkins_home

    alertmanager:
      container_name: alertmanager
      hostname: alertmanager
      image: prom/alertmanager
      volumes:
        - ./alertmanager.conf:/etc/alertmanager/alertmanager.conf
      command:
        - '--config.file=/etc/alertmanager/alertmanager.conf'
      ports:
        - 9093:9093

    prometheus:
      container_name: prometheus
      hostname: prometheus
      image: prom/prometheus
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
        - prometheus_data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      links:
        - alertmanager:alertmanager
      ports:
        - 9090:9090

    grafana:
      container_name: grafana
      hostname: grafana
      image: grafana/grafana
      volumes:
        - ./grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
        - ./grafana_config.ini:/etc/grafana/config.ini
        - grafana_data:/var/lib/grafana
      ports:
        - 3000:3000